#!/usr/bin/env julia

# using Pkg
# Pkg.activate(@__DIR__)

using Distributed
using Milk  # precompiled module

# Parse args
args = Milk.parse_arguments()
n_cpus = args["threads"]

# Add workers if needed
if nworkers() < n_cpus
    addprocs(n_cpus - nworkers())
end

# Make the module available on all workers
@everywhere using Milk

# Run main
Milk.main()