#!/usr/bin/env julia

# using Base.FileSystem
using ArgParse
using Logging
using Distributed

include("utils/utils.jl")
include("utils/cli.jl")
include("utils/file_handling.jl")

function parse_arguments()
    args = ArgParseSettings()
    @add_arg_table args begin
        "--input-path","-i" 
            arg_type = String
            required = true
            help = "Uncompressed CSV file. First column corresponds to object IDs (e.g., cell barcode). No header"
        "--batch-size","-b"
            arg_type = Int
            default = 50
            help = "[HPC mode] The number of partitioned input files to be assigned per job."
        "--sample-size","-n"
            arg_type = Int
            default = 1
            help = "Stopping point for recursion process. Sample size of 1 recurses until a single group remains."
        "--cache-size-limit","-c"
            arg_type = Int
            default = 50000
            help = "How many (representative) objects to cache for medoid optimization in subsequent recursions."
        "--partition-size","-p"
            arg_type = Int
            default = 10000
            help = "How many objects per partitioned file."
        "--merge-threshold","-M"
            arg_type = Int
            default = 100000
            help = "Threshold of when to carry out an additional merging stratification process (if exceeded, basic concatenation to join partitioned groups)"
        "--compile-previous-threshold","-P"
            arg_type = Int
            default = 1000000
            help = "Only carry forward previous groups if the number of representatives is below this threshold (tractability). TODO maybe delete"
        "--metric","-m"
            arg_type = String
            default = "euclidean"
            help = "Distance metric for pairwise comparisons. Permissible values: {'cosine','euclidean'})"
        "--label","-l"
            arg_type = String
            default = nothing
            help = ""
        "--percentile","-t"
            arg_type = Float64
            default = 1.0
            help = "Threshold for stratification process to group cells."
        "--threads","-T"
            arg_type = Int
            default = 1
            help = "Number of distrbuted processes. TODO change to n_cpus"
        "--seed","-r"
            arg_type = Int
            default = 21
            help = "Random seed"
        "--job-scheduler"
            arg_type = String
            default = "slurm"
            help = ""
        "--job-account"
            arg_type = String
            default = nothing
            help = ""
        "--job-name"
            arg_type = String
            default = "milk"
            help = ""
        "--job-memory"
            arg_type = Int
            default = 4
            help = ""
        "--job-time"
            arg_type = String
            default = ""
            help = "24:00:00"
        "--environment-path"
            arg_type = String
            default = nothing
            help = ""
        "--verbose"
            action = :store_true
            help = ""
        "--skip-reconstruction"
            action = :store_true
            help = ""
        "--output-dir","-o"
            arg_type = String
            default = "."
            help = ""
    end
    return parse_args(args)
end

function main()
    args = parse_arguments()

    n_cpus = args["threads"]
    n_workers = nworkers()
    if n_workers < n_cpus
        addprocs(n_cpus-n_workers)
        @everywhere include("utils/utils.jl")
        @everywhere include("utils/file_handling.jl")
    end

    logger = ConsoleLogger(stdout,Logging.Info)
    global_logger(logger)
    @info "milk"
    flush(stdout)

    log_args(args)

    invariant_args = instantiate_invariant_args(args)

    mkpath(invariant_args["output-dir"])

    if isnothing(args["label"])
        label = replace(basename(args["input-path"]),".csv" => "")
    else
        label = args["label"]
    end

    cache_path = nothing
    previous_groups_path = nothing

    # Initial recursion
    i = 0

    full_label = "$(label).iteration_$(lpad(string(i),3,'0'))"

    input_path = joinpath(invariant_args["output-dir"],"$(full_label).input.csv")
    symlink(abspath(args["input-path"]),input_path)

    n = get_object_count(input_path)

    @info "Iteration: $i ($n objects)"
    flush(stdout)

    # Pre-emptively set cache for subsequent recursions (no caching for initial iteration)
    cache_path = attempt_to_cache_file(input_path,n,invariant_args)

    if n <= args["partition-size"]
        recursive_processing(
            representatives_path=input_path,
            iteration=i,
            label=label,
            cache_path=cache_path,
            previous_groups_path=previous_groups_path,
            invariant_args=invariant_args
        )
    else
        representatives_path,groups_path = process(
            input_path=input_path,
            label=full_label,
            cache_path=nothing,
            previous_groups_path=nothing,
            invariant_args=invariant_args
        )

        n = get_object_count(representatives_path)
        if isnothing(cache_path)
            cache_path = attempt_to_cache_file(representatives_path,n,invariant_args)
        end
        # previous_groups_path = groups_path
        if n <= args["compile-previous-threshold"]
            previous_groups_path = groups_path
        end

        while n > args["sample-size"]
            if n <= args["partition-size"]
                recursive_processing(
                    representatives_path=representatives_path,
                    iteration=i,
                    label=label,
                    cache_path=cache_path,
                    previous_groups_path=previous_groups_path,
                    invariant_args=invariant_args
                )
                break
            end

            i += 1
            full_label = "$(label).iteration_$(lpad(string(i),3,'0'))"
            @info "Iteration: $i ($n objects)"
            flush(stdout)

            input_path = joinpath(invariant_args["output-dir"],"$(full_label).input.csv")
            symlink(representatives_path,input_path)

            representatives_path,groups_path = process(
                input_path=input_path,
                label=full_label,
                cache_path=cache_path,
                previous_groups_path=previous_groups_path,
                invariant_args=invariant_args
            )
            # previous_groups_path = groups_path
            n = get_object_count(representatives_path)
            if isnothing(cache_path)
                cache_path = attempt_to_cache_file(representatives_path,n,invariant_args)
            end
            if n <= args["compile-previous-threshold"]
                previous_groups_path = groups_path
            end
            @info "\t$n objects after recursive iteration."
            flush(stdout)
        end
    end

    @info "\nCompleted recursive downsampling procedure."
    flush(stdout)

    if args["skip-reconstruction"]
        @info "Skipping cell hierarchy reconstruction."
    else
        @info "Reconstructing hierarchical graph..."
        flush(stdout)
        command = [
            "julia",
            joinpath(@__DIR__,"hierarchical_reconstruction.jl"),
            "-i", args["input-dir"]
        ]
        command = Cmd(command)
        run(command)
    end
    @info "\tDone!"
    flush(stdout)
end

main()
